[preview.inputs]
type="hlssink2"
width=320
height=160
video_encoder.name = "openh264enc"
audio_encoder.name = "aac"

[preview.scenes]
type="hlssink2"
width=640
height=320
video_encoder.name = "openh264enc"
audio_encoder.name = "aac"

[preview.program]
type="hlssink2"
width=640
height=320
video_encoder.name = "openh264enc"
audio_encoder.name = "aac"

[main]

# Video
default_resolution = "HD720"
default_framerate = "30/1"

# Audio
volume = 0.7
audio_format = "S16LE"
audio_rate = 48000
audio_channels = 2

hls_path = "/var/dove/hls"


#preview settings
preview_format = "hls" # | webrtc
preview_resolution = "SmallPreview"
preview_enabled = true


[resolutions."QHD"]
{width = 2560, height = 1440}
[resolutions."FullHD"]
{width = 1920, height = 1080}
[resolutions."WSXGA"]
{width = 1600, height = 900}
[resolutions."WXGA"]
{width = 1366, height =  768}
[resolutions."HD720"]
{width = 1280, height = 720}
[resolutions."WSVGA"]
{width = 1024, height = 576}
[resolutions."qHD"]
{width = 960, height = 540}
[resolutions."Preview"]
{width = 480, height = 270}
[resolutions."SmallPreview"]
{width = 320, height = 180}


[ui]
add_input = true
add_scene = true
add_output = true
input_preview_auto= true



[scenes]


[inputs]


[outputs]

