[main]

# Video
resolution = "HD720"
framerate = "30/1"

# Audio
volume = 0.7
audio_format = "F32LE"
audio_rate = 48000
audio_channels = 2

hls_path = "/var/dove/hls"


#preview settings
preview_format = "hls" # | webrtc
preview_resolution = "SmallPreview"
preview_enabled = true


[resolutions."QHD"]
{width = 2560, height = 1440}
[resolutions."FullHD"]
{width = 1920, height = 1080}
[resolutions."WSXGA"]
{width = 1600, height = 900}
[resolutions."WXGA"]
{width = 1366, height =  768}
[resolutions."HD720"]
{width = 1280, height = 720}
[resolutions."WSVGA"]
{width = 1024, height = 576}
[resolutions."qHD"]
{width = 960, height = 540}
[resolutions."Preview"]
{width = 480, height = 270}
[resolutions."SmallPreview"]
{width = 320, height = 180}


[ui]
add_input = true
add_mixer = true
add_output = true
input_preview_auto= true
enabled_inputs = ["playbin3", "wpesrc", "ytdlp", "testsrc"]
enabled_outputs = ["srtsink", "decklink", "shout2send"]


[scenes]


[inputs]


[outputs]
