version: "3.5"
services:
  dove:
    image: ghcr.io/dorftv/dove:latest
    build:
      context: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - DISPLAY=$DISPLAY
      - LOG_LEVEL=debug

    restart: always
    ports:
      - 5000:5000
    networks:
      - dove
networks:
  dove:

