version: "3.5"
services:
  frontend:
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: npm run dev -- -o --host
    expose:
      - 8000
    volumes:
      - ./frontend/:/var/www/html/app
    tty: true
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    environment:
      - GST_DEBUG=3
      - LOG_LEVEL=debug
      - LIBGL_ALWAYS_SOFTWARE=true
      - LIBVA_DRIVER_NAME=fakedrive
      - GST_PLUGIN_FEATURE_RANK="wpesrc:MAX"
    restart: always
    ports:
      - 5000:5000
      - 8080:8080

networks:
  dove:

