version: "3.5"
services:
  dove:
    image: ghcr.io/dorftv/dove:latest
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - LOG_LEVEL=debug
    restart: always
    ports:
      - 5000:5000
    networks:
      - dove
networks:
  dove:

