[tool.poetry]
name = "dove"
version = "0.1"
description = "DORFTV Online Video Editor"
authors = ["Stefan Hageneder <stefan.hageneder@dorftv.at>"]
license = "Apache License"
#readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.111.0"
uvicorn = "^0.24.0.post1"
websockets = "^12.0"
orjson = "^3.10.3"
toml = "^0.10.2"
yt-dlp = "^2024.5.26"
graphviz = "^0.20.3"
pydantic = "^2.7.1"
pygobject = "^3.48.2"
gobject = "^0.1.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
include-package-data = false
py-modules = []
