[tool.poetry]
name = "dove"
version = "0.1"
description = "DORFTV Online Video Editor"
authors = ["Stefan Hageneder <stefan.hageneder@dorftv.at>"]
license = "Apache License"
#readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
websockets = "^12.0"
orjson = "3.9.10"
toml = "^0.10.2"
yt-dlp = "^2024.03.10"
graphviz = "^0.20.2"
#needed or better from system?
#pygobject = "^3.48.2"
#gobject = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools]
include-package-data = false
py-modules = []
